---
Name: progressivewebapp
---

SilverStripe\Control\Director:
  rules:
    'manifest.json': 'A2nt\ProgressiveWebApp\Controllers\ManifestController'
    'sw.js/$Action': 'A2nt\ProgressiveWebApp\Controllers\ServiceWorkerController'

SilverStripe\CMS\Model\SiteTree:
  extensions:
    - A2nt\ProgressiveWebApp\Extensions\SiteTree
