---
Name: progressivewebapp
---

SilverStripe\Control\Director:
  rules:
    'manifest.json': 'A2nt\ProgressiveWebApp\Controllers\ManifestController'
    'service-worker.js': 'A2nt\ProgressiveWebApp\Controllers\ServiceWorkerController'
